# Generated by Django 5.2.7 on 2025-10-10 13:33

import core.models
import django.db.models.deletion
import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Centro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado",
                    models.DateField(auto_now_add=True, verbose_name="Data de Criação"),
                ),
                (
                    "modificado",
                    models.DateField(auto_now=True, verbose_name="Data de Atualização"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo?")),
                ("nome", models.CharField(max_length=150, verbose_name="Nome")),
                ("endereco", models.CharField(max_length=200, verbose_name="Endereço")),
                ("bairro", models.CharField(max_length=60, verbose_name="Bairro")),
                ("cidade", models.CharField(max_length=100, verbose_name="Cidade")),
                ("cep", models.CharField(max_length=50, verbose_name="CEP")),
                ("ano", models.CharField(max_length=4, verbose_name="Ano")),
                ("url", models.CharField(max_length=100, verbose_name="Url")),
                (
                    "imagem",
                    stdimage.models.StdImageField(
                        force_min_size=False,
                        upload_to="media",
                        variations={"thumb": (124, 124)},
                        verbose_name="Imagem",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, editable=False, max_length=100, verbose_name="Slug"
                    ),
                ),
            ],
            options={"verbose_name": "Centro", "verbose_name_plural": "Centros",},
        ),
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado",
                    models.DateField(auto_now_add=True, verbose_name="Data de Criação"),
                ),
                (
                    "modificado",
                    models.DateField(auto_now=True, verbose_name="Data de Atualização"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo?")),
                ("evento", models.CharField(max_length=100, verbose_name="Evento")),
                (
                    "descricao",
                    models.TextField(max_length=500, verbose_name="Descricao"),
                ),
                (
                    "palestrante",
                    models.CharField(max_length=100, verbose_name="Palestrante"),
                ),
                ("endereco", models.CharField(max_length=200, verbose_name="Endereço")),
                ("bairro", models.CharField(max_length=60, verbose_name="Bairro")),
                ("cidade", models.CharField(max_length=100, verbose_name="Cidade")),
                ("cep", models.CharField(max_length=50, verbose_name="CEP")),
                ("ano", models.CharField(max_length=4, verbose_name="Ano")),
                ("url", models.CharField(max_length=100, verbose_name="Url")),
                (
                    "imagem",
                    stdimage.models.StdImageField(
                        force_min_size=False,
                        upload_to="media",
                        variations={"thumb": (124, 124)},
                        verbose_name="Imagem",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, editable=False, max_length=100, verbose_name="Slug"
                    ),
                ),
            ],
            options={"verbose_name": "Evento", "verbose_name_plural": "Eventos",},
        ),
        migrations.CreateModel(
            name="Livro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado",
                    models.DateField(auto_now_add=True, verbose_name="Data de Criação"),
                ),
                (
                    "modificado",
                    models.DateField(auto_now=True, verbose_name="Data de Atualização"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo?")),
                ("titulo", models.CharField(max_length=100, verbose_name="Titulo")),
                ("sinopse", models.TextField(max_length=500, verbose_name="Sinopse")),
                ("autor", models.CharField(max_length=60, verbose_name="Autor")),
                ("espirito", models.CharField(max_length=100, verbose_name="Espirito")),
                ("editora", models.CharField(max_length=50, verbose_name="Editora")),
                ("ano", models.CharField(max_length=4, verbose_name="Ano")),
                (
                    "url",
                    models.FileField(
                        upload_to=core.models.get_file_path_livro, verbose_name="Url"
                    ),
                ),
                (
                    "imagem",
                    stdimage.models.StdImageField(
                        force_min_size=False,
                        upload_to="media",
                        variations={"thumb": (124, 124)},
                        verbose_name="Imagem",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, editable=False, max_length=100, verbose_name="Slug"
                    ),
                ),
            ],
            options={"verbose_name": "Livro", "verbose_name_plural": "Livros",},
        ),
        migrations.CreateModel(
            name="Mensagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado",
                    models.DateField(auto_now_add=True, verbose_name="Data de Criação"),
                ),
                (
                    "modificado",
                    models.DateField(auto_now=True, verbose_name="Data de Atualização"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo?")),
                ("titulo", models.CharField(max_length=100, verbose_name="Titulo")),
                ("mensagem", models.TextField(max_length=500, verbose_name="Mensagem")),
                ("autor", models.CharField(max_length=60, verbose_name="Autor")),
                ("fonte", models.CharField(max_length=100, verbose_name="Fonte")),
                (
                    "imagem",
                    stdimage.models.StdImageField(
                        force_min_size=False,
                        upload_to="media",
                        variations={"thumb": (124, 124)},
                        verbose_name="Imagem",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, editable=False, max_length=100, verbose_name="Slug"
                    ),
                ),
            ],
            options={"verbose_name": "Mensagem", "verbose_name_plural": "Mensagens",},
        ),
        migrations.CreateModel(
            name="Musica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado",
                    models.DateField(auto_now_add=True, verbose_name="Data de Criação"),
                ),
                (
                    "modificado",
                    models.DateField(auto_now=True, verbose_name="Data de Atualização"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo?")),
                (
                    "subtitulo",
                    models.CharField(max_length=100, verbose_name="Subtitulo"),
                ),
                (
                    "descricao",
                    models.TextField(max_length=500, verbose_name="Descricao"),
                ),
                ("cantor", models.CharField(max_length=100, verbose_name="Cantor")),
                (
                    "compositor",
                    models.CharField(max_length=100, verbose_name="Compositor"),
                ),
                ("ano", models.CharField(max_length=4, verbose_name="Ano")),
                (
                    "url",
                    models.FileField(
                        upload_to=core.models.get_file_path_musica, verbose_name="Url"
                    ),
                ),
                (
                    "imagem",
                    stdimage.models.StdImageField(
                        force_min_size=False,
                        upload_to="media",
                        variations={"thumb": (124, 124)},
                        verbose_name="Imagem",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, editable=False, max_length=100, verbose_name="Slug"
                    ),
                ),
            ],
            options={"verbose_name": "Música", "verbose_name_plural": "Músicas",},
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado",
                    models.DateField(auto_now_add=True, verbose_name="Data de Criação"),
                ),
                (
                    "modificado",
                    models.DateField(auto_now=True, verbose_name="Data de Atualização"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo?")),
                (
                    "subtitulo",
                    models.CharField(max_length=100, verbose_name="Subtitulo"),
                ),
                (
                    "descricao",
                    models.TextField(max_length=500, verbose_name="Descricao"),
                ),
                ("autor", models.CharField(max_length=100, verbose_name="Autor")),
                ("ano", models.CharField(max_length=4, verbose_name="Ano")),
                (
                    "url",
                    models.FileField(
                        upload_to=core.models.get_file_path_video, verbose_name="Url"
                    ),
                ),
                (
                    "imagem",
                    stdimage.models.StdImageField(
                        force_min_size=False,
                        upload_to="media",
                        variations={"thumb": (124, 124)},
                        verbose_name="Imagem",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, editable=False, max_length=100, verbose_name="Slug"
                    ),
                ),
            ],
            options={"verbose_name": "Vídeo", "verbose_name_plural": "Vídeos",},
        ),
        migrations.CreateModel(
            name="Social",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado",
                    models.DateField(auto_now_add=True, verbose_name="Data de Criação"),
                ),
                (
                    "modificado",
                    models.DateField(auto_now=True, verbose_name="Data de Atualização"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo?")),
                (
                    "atividade",
                    models.CharField(max_length=150, verbose_name="Atividade"),
                ),
                (
                    "descricao",
                    models.TextField(max_length=500, verbose_name="Descrição"),
                ),
                ("dia", models.CharField(max_length=50, verbose_name="Dia")),
                ("hora", models.CharField(max_length=50, verbose_name="Hora")),
                (
                    "responsavel",
                    models.CharField(max_length=100, verbose_name="Resposável"),
                ),
                (
                    "imagem",
                    stdimage.models.StdImageField(
                        force_min_size=False,
                        upload_to="media",
                        variations={"thumb": (124, 124)},
                        verbose_name="Imagem",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, editable=False, max_length=100, verbose_name="Slug"
                    ),
                ),
                (
                    "id_centro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.centro",
                        verbose_name="Centro",
                    ),
                ),
            ],
            options={"verbose_name": "Social", "verbose_name_plural": "Sociais",},
        ),
    ]
