# Generated by Django 5.2.7 on 2025-10-18 11:55

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="social", name="id_centro",),
        migrations.AddField(
            model_name="centro",
            name="evento",
            field=models.ManyToManyField(blank=True, to="core.evento"),
        ),
        migrations.AddField(
            model_name="centro",
            name="social",
            field=models.ManyToManyField(blank=True, to="core.social"),
        ),
        migrations.AddField(
            model_name="livro",
            name="pdf",
            field=models.FileField(
                blank=True,
                upload_to=core.models.get_file_path_livro,
                verbose_name="Pdf",
            ),
        ),
        migrations.AddField(
            model_name="musica",
            name="musica",
            field=models.FileField(
                blank=True,
                upload_to=core.models.get_file_path_musica,
                verbose_name="Musica",
            ),
        ),
        migrations.AddField(
            model_name="video",
            name="video",
            field=models.FileField(
                blank=True,
                upload_to=core.models.get_file_path_video,
                verbose_name="Video",
            ),
        ),
        migrations.AlterField(
            model_name="centro",
            name="url",
            field=models.URLField(max_length=100, verbose_name="Url"),
        ),
        migrations.AlterField(
            model_name="evento",
            name="url",
            field=models.URLField(max_length=100, verbose_name="Url"),
        ),
        migrations.AlterField(
            model_name="livro",
            name="url",
            field=models.URLField(max_length=100, verbose_name="Url"),
        ),
        migrations.AlterField(
            model_name="musica", name="url", field=models.URLField(max_length=100),
        ),
        migrations.AlterField(
            model_name="social", name="dia", field=models.DateField(verbose_name="Dia"),
        ),
        migrations.AlterField(
            model_name="social",
            name="hora",
            field=models.TimeField(verbose_name="Hora"),
        ),
        migrations.AlterField(
            model_name="video",
            name="url",
            field=models.URLField(max_length=100, verbose_name="Url"),
        ),
        migrations.CreateModel(
            name="Destaque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado",
                    models.DateField(auto_now_add=True, verbose_name="Data de Criação"),
                ),
                (
                    "modificado",
                    models.DateField(auto_now=True, verbose_name="Data de Atualização"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo?")),
                (
                    "id_livro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.livro",
                        verbose_name="Livro",
                    ),
                ),
                (
                    "id_mensagem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.mensagem",
                        verbose_name="Mensagem",
                    ),
                ),
                (
                    "id_musica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.musica",
                        verbose_name="Musica",
                    ),
                ),
                (
                    "id_video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.video",
                        verbose_name="Video",
                    ),
                ),
            ],
            options={"verbose_name": "Destaque", "verbose_name_plural": "Destaques",},
        ),
    ]
