# Generated by Django 5.2.7 on 2025-10-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_social_id_centro_centro_evento_centro_social_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="centro",
            name="missao",
            field=models.TextField(blank=True, max_length=400, verbose_name="Missao"),
        ),
        migrations.AlterField(
            model_name="centro",
            name="ano",
            field=models.CharField(blank=True, max_length=4, verbose_name="Ano"),
        ),
        migrations.AlterField(
            model_name="centro",
            name="cep",
            field=models.CharField(blank=True, max_length=50, verbose_name="CEP"),
        ),
        migrations.AlterField(
            model_name="centro",
            name="url",
            field=models.URLField(blank=True, max_length=100, verbose_name="Url"),
        ),
    ]
