# Generated by Django 5.2.7 on 2025-10-22 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_centro_missao_alter_centro_ano_alter_centro_cep_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="social",
            name="atividade",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Atividade"
            ),
        ),
        migrations.AlterField(
            model_name="social",
            name="descricao",
            field=models.TextField(
                blank=True, max_length=500, verbose_name="Descrição"
            ),
        ),
        migrations.AlterField(
            model_name="social",
            name="dia",
            field=models.CharField(blank=True, max_length=250, verbose_name="Dia"),
        ),
        migrations.AlterField(
            model_name="social",
            name="hora",
            field=models.TimeField(blank=True, verbose_name="Hora"),
        ),
    ]
