# Generated by Django 5.2.7 on 2025-10-26 13:43

import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_social_atividade_alter_social_descricao_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="social",
            name="hora",
            field=models.CharField(blank=True, verbose_name="Hora"),
        ),
        migrations.AlterField(
            model_name="social",
            name="imagem",
            field=stdimage.models.StdImageField(
                blank=True,
                force_min_size=False,
                upload_to="media",
                variations={"thumb": (124, 124)},
                verbose_name="Imagem",
            ),
        ),
        migrations.AlterField(
            model_name="social",
            name="responsavel",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Resposável"
            ),
        ),
    ]
