# Generated by Django 5.2.7 on 2025-10-26 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_social_hora_alter_social_imagem_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="social",
            name="icon",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
