# Generated by Django 5.2.7 on 2025-10-26 19:30

import core.models
import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_social_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="social",
            name="icon",
            field=models.ImageField(
                blank=True, upload_to=core.models.get_file_path_icone
            ),
        ),
        migrations.AlterField(
            model_name="social",
            name="imagem",
            field=stdimage.models.StdImageField(
                blank=True,
                force_min_size=False,
                upload_to=core.models.get_file_path_social,
                variations={"thumb": (400, 400)},
                verbose_name="Imagem",
            ),
        ),
    ]
