# Generated by Django 5.2.7 on 2025-10-29 15:40

import django.db.models.deletion
import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_social_icon_alter_social_imagem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="musica",
            name="imagem",
            field=stdimage.models.StdImageField(
                blank=True,
                force_min_size=False,
                upload_to="media",
                variations={"thumb": (400, 400)},
                verbose_name="Imagem",
            ),
        ),
        migrations.AlterField(
            model_name="musica",
            name="url",
            field=models.URLField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="video",
            name="imagem",
            field=stdimage.models.StdImageField(
                blank=True,
                force_min_size=False,
                upload_to="media",
                variations={"thumb": (400, 400)},
                verbose_name="Imagem",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="url",
            field=models.URLField(blank=True, max_length=100, verbose_name="Url"),
        ),
        migrations.CreateModel(
            name="Citacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado",
                    models.DateField(auto_now_add=True, verbose_name="Data de Criação"),
                ),
                (
                    "modificado",
                    models.DateField(auto_now=True, verbose_name="Data de Atualização"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo?")),
                ("titulo", models.CharField(max_length=255, verbose_name="Titulo")),
                ("citacao", models.TextField(max_length=500, verbose_name="Citacao")),
                (
                    "autor",
                    models.CharField(blank=True, max_length=100, verbose_name="Autor"),
                ),
                (
                    "livro_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.livro",
                        verbose_name="Livro",
                    ),
                ),
            ],
            options={"verbose_name": "Citação", "verbose_name_plural": "Citações",},
        ),
    ]
