# Generated by Django 5.2.7 on 2025-11-02 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_musica_imagem_alter_musica_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="musica",
            name="youtube",
            field=models.URLField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="video",
            name="youtube",
            field=models.URLField(blank=True, max_length=150),
        ),
    ]
