# Generated by Django 5.2.7 on 2025-12-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_musica_youtube_video_youtube"),
    ]

    operations = [
        migrations.AddField(
            model_name="centro",
            name="facebook",
            field=models.URLField(blank=True, max_length=100, verbose_name="Facebook"),
        ),
        migrations.AddField(
            model_name="centro",
            name="instagram",
            field=models.URLField(blank=True, max_length=100, verbose_name="Instagram"),
        ),
        migrations.AddField(
            model_name="centro",
            name="youtube",
            field=models.URLField(blank=True, max_length=100, verbose_name="Youtube"),
        ),
        migrations.AddField(
            model_name="social",
            name="contato",
            field=models.CharField(blank=True, max_length=20, verbose_name="Contato"),
        ),
    ]
