# Generated by Django 5.2.7 on 2025-12-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_centro_facebook_centro_instagram_centro_youtube_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="centro",
            name="telefone",
            field=models.CharField(blank=True, max_length=25, verbose_name="Telefone"),
        ),
    ]
