# Generated by Django 5.2.7 on 2025-12-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_centro_telefone"),
    ]

    operations = [
        migrations.AddField(
            model_name="centro",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                default=0,
                max_digits=12,
                verbose_name="Latitude",
            ),
        ),
        migrations.AddField(
            model_name="centro",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                default=0,
                max_digits=12,
                verbose_name="Longitude",
            ),
        ),
    ]
