# Generated by Django 5.2.7 on 2025-12-29 17:43

import core.models
import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_centro_latitude_centro_longitude"),
    ]

    operations = [
        migrations.CreateModel(
            name="Temas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado",
                    models.DateField(auto_now_add=True, verbose_name="Data de Criação"),
                ),
                (
                    "modificado",
                    models.DateField(auto_now=True, verbose_name="Data de Atualização"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo?")),
                ("tema", models.CharField(max_length=50, verbose_name="Tema")),
                ("subtema", models.CharField(max_length=250, verbose_name="Subtema")),
                (
                    "descricao",
                    models.TextField(max_length=500, verbose_name="Descricao"),
                ),
                (
                    "imagem",
                    stdimage.models.StdImageField(
                        force_min_size=False,
                        upload_to=core.models.get_file_path_tema,
                        variations={},
                        verbose_name="Imagem",
                    ),
                ),
            ],
            options={"verbose_name": "Tema", "verbose_name_plural": "Temas",},
        ),
    ]
