# Generated by Django 5.2.9 on 2026-02-18 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_temas"),
    ]

    operations = [
        migrations.CreateModel(
            name="Materia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado",
                    models.DateField(auto_now_add=True, verbose_name="Data de Criação"),
                ),
                (
                    "modificado",
                    models.DateField(auto_now=True, verbose_name="Data de Atualização"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo?")),
                ("materia", models.CharField(max_length=255, verbose_name="Materia")),
                ("conteudo", models.TextField(verbose_name="Conteúdo")),
                (
                    "autor",
                    models.CharField(blank=True, max_length=200, verbose_name="Autor"),
                ),
                (
                    "tema_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.temas",
                        verbose_name="Temas",
                    ),
                ),
            ],
            options={"verbose_name": "Materia", "verbose_name_plural": "Materias",},
        ),
    ]
